version: 0.2

phases:
  build:
    commands:
      - yes | sudo sdkmanager --licenses
      - bash ./gradlew assembleDebug
  post_build:
    commands:
      - echo "******** Uploading to S3 ********"
      - aws s3 cp app/build/outputs/apk/app-debug.apk s3://fantasyeplmatchtracker/bin/fantasyeplmatchtracker.apk
artifacts:
  files:
    - app/build/outputs/apk/app-debug.apk
  discard-paths: yes
