version: 0.2

phases:
  build:
    commands:
      - mkdir "$ANDROID_HOME/licenses" || true
      - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
      - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
      - echo y | android update sdk --no-ui --all --filter "tool,extra-android-m2repository,extra-android-support,extra-google-google_play_services,extra-google-m2repository"
      - chmod a+x ./gradlew
      - ./gradlew assembleDebug
  post_build:
    commands:
      - echo "******** Uploading to S3 ********"
      - aws s3 cp app/build/outputs/apk/app-debug.apk s3://fantasyeplmatchtracker/bin/fantasyeplmatchtracker.apk
artifacts:
  files:
    - app/build/outputs/apk/app-debug.apk
  discard-paths: yes
